version: "3"
networks:
    splash_net:
      driver: bridge
services:
  splash001:
    image: scrapinghub/splash
    container_name: splash001
    networks:
      - splash_net
    restart: always
  splash002:
    image: scrapinghub/splash
    container_name: splash002
    networks:
      - splash_net
    restart: always
  splash003:
    image: scrapinghub/splash
    container_name: splash003
    networks:
      - splash_net
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - splash_net
    volumes:
      - ./docker/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/var/www
      - /etc/letsencrypt:/etc/letsencrypt
  
